version: '2'
services:
  proxy:
    build: ./proxy
    links: 
      - redis 
    ports:
      - 50103:3002
  hw3: 
    build: ./node
    links: 
      - redis
    ports:
      - 50102:3000
  redis:
    image: redis
    ports: 
      - "6379"
volumes:
  logvolume01: {}
